//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlBox.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCiudades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCiudades()
        {
            this.TGiros = new HashSet<TGiros>();
        }
    
        public int Ciudad_id { get; set; }
        public int Pais_id { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TGiros> TGiros { get; set; }
        public virtual TPaises TPaises { get; set; }
    }
}
