//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlBox.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGiros
    {
        public int Giro_id { get; set; }
        public int Ciudad_id { get; set; }
        public string Recibo { get; set; }
    
        public virtual TCiudades TCiudades { get; set; }
    }
}
