//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlBox.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCiudades
    {
        public int Pais_id { get; set; }
        public string NombrePais { get; set; }
        public string NombreCiudad { get; set; }
        public int Ciudad_id { get; set; }
    }
}
